apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ch-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ch-operator
  template:
    metadata:
      labels:
        name: ch-operator
    spec:
      serviceAccountName: ch-operator
      containers:
        - name: ch-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - ch-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ch-operator"
