apiVersion: clickhouse.xiedeyantu.com/v1beta1
kind: ClickHouseCluster
metadata:
  name: chcluster
spec:
  zookeeper:
    name: zookeeper
    replicas: 3
    image:
      repository: zookeeper
      tag: 3.6.1
      pullPolicy: IfNotPresent
    storageType: ephemeral
    persistence:
      reclaimPolicy: Delete
      spec:
        storageClassName: "default"
        resources:
          requests:
            storage: 20Gi

  clickhouse:
    name: clickhouse
    shards: 2
    replicas: 2
    image:
      repository: xiedeyantu/clickhouse-server
      tag: 20.3.18.10
      pullPolicy: IfNotPresent
    storageType: ephemeral
    persistence:
      reclaimPolicy: Delete
      spec:
        storageClassName: "default"
        resources:
          requests:
            storage: 20Gi