apiVersion: apps/v1
kind: Deployment
metadata:
  name: ch-operator
spec:
  replicas: {{ .Values.chOperator.replicas }}
  selector:
    matchLabels:
      name: ch-operator
  template:
    metadata:
      labels:
        name: ch-operator
    spec:
      serviceAccountName: ch-operator
      containers:
        - name: ch-operator
          imagePullPolicy: {{ .Values.chOperator.imagePullPolicy }}
          image: {{ .Values.chOperator.image }}:{{ .Values.chOperator.imageVersion }}
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ch-operator"
